import type { SafetyRule } from './types'

/**
 * Production safety rules.
 * Paths use `~` / `%ENV%` — never hardcode a specific username.
 * Higher `priority` wins when multiple rules match.
 */
export const SAFETY_RULES: SafetyRule[] = [
  // ─── Windows OS / boot ─────────────────────────────────────────────
  {
    id: 'win-system-root',
    platforms: ['win32'],
    pathPattern: '%SystemRoot%/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'Windows system files — deleting these can crash or prevent Windows from starting.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 900
  },
  {
    id: 'win-winsxs',
    platforms: ['win32'],
    pathPattern: '%SystemRoot%/WinSxS/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'Windows component store (WinSxS) — required for updates and system integrity.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 950
  },
  {
    id: 'win-program-files',
    platforms: ['win32'],
    pathPattern: '%ProgramFiles%/**',
    risk: 'PROTECTED',
    category: 'installed-apps',
    reason: 'Installed application files — removing them can break programs.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 880
  },
  {
    id: 'win-program-files-x86',
    platforms: ['win32'],
    pathPattern: '%ProgramFiles(x86)%/**',
    risk: 'PROTECTED',
    category: 'installed-apps',
    reason: 'Installed application files — removing them can break programs.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 880
  },
  {
    id: 'win-programdata-microsoft',
    platforms: ['win32'],
    pathPattern: '%ProgramData%/Microsoft/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'Windows ProgramData — used by the OS and security components.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 860
  },
  {
    id: 'win-recovery',
    platforms: ['win32'],
    pathPattern: '%SystemDrive%/Recovery/**',
    risk: 'PROTECTED',
    category: 'os-boot',
    reason: 'Windows recovery partition data — required to repair the system.',
    scanAllowed: false,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 920
  },
  {
    id: 'win-efi',
    platforms: ['win32'],
    pathPattern: '%SystemDrive%/EFI/**',
    risk: 'PROTECTED',
    category: 'os-boot',
    reason: 'Boot firmware data — deleting this can make the PC unbootable.',
    scanAllowed: false,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 920
  },
  {
    id: 'win-user-temp',
    platforms: ['win32'],
    pathPattern: '%LOCALAPPDATA%/Temp/**',
    risk: 'CAUTION',
    category: 'temp',
    reason: 'Temporary files — usually safe, but apps may recreate them on next launch.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 400,
    regeneratable: true,
    recoverable: false
  },

  // ─── macOS OS ──────────────────────────────────────────────────────
  {
    id: 'mac-system',
    platforms: ['darwin'],
    pathPattern: '/System/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'macOS system files — deleting these can make the Mac unstable or unbootable.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 900
  },
  {
    id: 'mac-usr',
    platforms: ['darwin'],
    pathPattern: '/usr/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'macOS system utilities — required for the operating system.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 880
  },
  {
    id: 'mac-bin',
    platforms: ['darwin'],
    pathPattern: '/bin/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'Core system binaries — required for macOS to function.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 880
  },
  {
    id: 'mac-sbin',
    platforms: ['darwin'],
    pathPattern: '/sbin/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'Core system binaries — required for macOS to function.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 880
  },
  {
    id: 'mac-library-system',
    platforms: ['darwin'],
    pathPattern: '/Library/**',
    risk: 'HIGH_RISK',
    category: 'os-system',
    reason: 'System Library — shared by macOS and installed apps; deleting may break software.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 700
  },
  {
    id: 'mac-applications',
    platforms: ['darwin'],
    pathPattern: '/Applications/**',
    risk: 'PROTECTED',
    category: 'installed-apps',
    reason: 'Installed applications — removing files here can break apps.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 850
  },
  {
    id: 'mac-user-library-preferences',
    platforms: ['darwin'],
    pathPattern: '~/Library/Preferences/**',
    risk: 'HIGH_RISK',
    category: 'user-identity',
    reason: 'App preferences — deleting these resets settings and may break workflows.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 720
  },
  {
    id: 'mac-user-library-keychains',
    platforms: ['darwin'],
    pathPattern: '~/Library/Keychains/**',
    risk: 'PROTECTED',
    category: 'user-identity',
    reason: 'Keychain passwords and certificates — deleting these can lock you out of accounts.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 940
  },
  {
    id: 'mac-derived-data',
    platforms: ['darwin'],
    pathPattern: '~/Library/Developer/Xcode/DerivedData/**',
    risk: 'CAUTION',
    category: 'dev-cache',
    reason: 'Xcode DerivedData — regeneratable, but the next build may take longer.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 520,
    regeneratable: true
  },
  {
    id: 'mac-library-developer',
    platforms: ['darwin'],
    pathPattern: '~/Library/Developer/**',
    risk: 'HIGH_RISK',
    category: 'dev-tooling',
    reason: 'Apple developer tools data — deleting may break Xcode or simulators.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 500
  },
  {
    id: 'mac-library-android',
    platforms: ['darwin'],
    pathPattern: '~/Library/Android/**',
    risk: 'HIGH_RISK',
    category: 'dev-tooling',
    reason: 'Android SDK / emulator files — deleting may break Android builds.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 500
  },
  {
    id: 'mac-library-java',
    platforms: ['darwin'],
    pathPattern: '~/Library/Java/**',
    risk: 'HIGH_RISK',
    category: 'dev-tooling',
    reason: 'Java runtime installs — deleting may break JVM-based tools.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 500
  },
  {
    id: 'mac-user-caches',
    platforms: ['darwin'],
    pathPattern: '~/Library/Caches/**',
    risk: 'CAUTION',
    category: 'cache',
    reason: 'App caches — usually regeneratable, but apps may run slower until rebuilt.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 350,
    regeneratable: true
  },

  // ─── Linux OS ──────────────────────────────────────────────────────
  {
    id: 'linux-boot',
    platforms: ['linux'],
    pathPattern: '/boot/**',
    risk: 'PROTECTED',
    category: 'os-boot',
    reason: 'Boot files — deleting these can prevent Linux from starting.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 920
  },
  {
    id: 'linux-etc',
    platforms: ['linux'],
    pathPattern: '/etc/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'System configuration — deleting these can break the OS and services.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 900
  },
  {
    id: 'linux-usr',
    platforms: ['linux'],
    pathPattern: '/usr/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'System and application files under /usr — required for a working system.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 880
  },
  {
    id: 'linux-bin',
    platforms: ['linux'],
    pathPattern: '/bin/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'Core system binaries — required for Linux to function.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 880
  },
  {
    id: 'linux-sbin',
    platforms: ['linux'],
    pathPattern: '/sbin/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'Core system binaries — required for Linux to function.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 880
  },
  {
    id: 'linux-lib',
    platforms: ['linux'],
    pathPattern: '/lib/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'System libraries — deleting these can crash applications and the OS.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 880
  },
  {
    id: 'linux-lib64',
    platforms: ['linux'],
    pathPattern: '/lib64/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'System libraries — deleting these can crash applications and the OS.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 880
  },
  {
    id: 'linux-proc',
    platforms: ['linux'],
    pathPattern: '/proc/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'Virtual process filesystem — not real files and must not be modified.',
    scanAllowed: false,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 950
  },
  {
    id: 'linux-sys',
    platforms: ['linux'],
    pathPattern: '/sys/**',
    risk: 'PROTECTED',
    category: 'os-system',
    reason: 'Virtual sysfs — not real files and must not be modified.',
    scanAllowed: false,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 950
  },
  {
    id: 'linux-user-cache',
    platforms: ['linux'],
    pathPattern: '~/.cache/**',
    risk: 'CAUTION',
    category: 'cache',
    reason: 'User cache — usually regeneratable, but apps may re-download data.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 350,
    regeneratable: true
  },

  // ─── Cross-platform developer tooling ──────────────────────────────
  {
    id: 'gradle-wrapper-dists',
    platforms: ['all'],
    pathPattern: '~/.gradle/wrapper/dists/**',
    risk: 'PROTECTED',
    category: 'dev-tooling',
    reason:
      'Gradle distribution files required by development builds. Deleting them can break Android, Expo, and other Gradle projects.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 800,
    regeneratable: false
  },
  {
    id: 'gradle-wrapper',
    platforms: ['all'],
    pathPattern: '~/.gradle/wrapper/**',
    risk: 'PROTECTED',
    category: 'dev-tooling',
    reason: 'Gradle wrapper data — required to download and run Gradle distributions.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 750
  },
  {
    id: 'gradle-caches',
    platforms: ['all'],
    pathPattern: '~/.gradle/caches/**',
    risk: 'CAUTION',
    category: 'dev-cache',
    reason:
      'Gradle dependency cache — regeneratable, but the next build may re-download packages.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 600,
    regeneratable: true
  },
  {
    id: 'gradle-home',
    platforms: ['all'],
    pathPattern: '~/.gradle/**',
    risk: 'HIGH_RISK',
    category: 'dev-tooling',
    reason: 'Gradle user home — contains tool state used by development builds.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 550
  },
  {
    id: 'maven-repo',
    platforms: ['all'],
    pathPattern: '~/.m2/**',
    risk: 'CAUTION',
    category: 'dev-cache',
    reason: 'Maven local repository — regeneratable, but builds may re-download artifacts.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 500,
    regeneratable: true
  },
  {
    id: 'npm-cache',
    platforms: ['all'],
    pathPattern: '~/.npm/**',
    risk: 'CAUTION',
    category: 'dev-cache',
    reason: 'npm cache — regeneratable; packages may be re-downloaded later.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 500,
    regeneratable: true
  },
  {
    id: 'pnpm-store',
    platforms: ['all'],
    pathPattern: '~/.pnpm-store/**',
    risk: 'CAUTION',
    category: 'dev-cache',
    reason: 'pnpm content-addressable store — regeneratable but large re-downloads possible.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 500,
    regeneratable: true
  },
  {
    id: 'yarn-cache',
    platforms: ['all'],
    pathPattern: '~/.yarn/**',
    risk: 'CAUTION',
    category: 'dev-cache',
    reason: 'Yarn cache / state — regeneratable; installs may take longer afterward.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 500,
    regeneratable: true
  },
  {
    id: 'cargo-registry',
    platforms: ['all'],
    pathPattern: '~/.cargo/**',
    risk: 'CAUTION',
    category: 'dev-cache',
    reason: 'Rust Cargo registry/cache — regeneratable; next builds may re-fetch crates.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 500,
    regeneratable: true
  },
  {
    id: 'rustup',
    platforms: ['all'],
    pathPattern: '~/.rustup/**',
    risk: 'HIGH_RISK',
    category: 'dev-tooling',
    reason: 'Rust toolchains — deleting them breaks Rust development until reinstalled.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 650
  },
  {
    id: 'android-home',
    platforms: ['all'],
    pathPattern: '~/.android/**',
    risk: 'HIGH_RISK',
    category: 'dev-tooling',
    reason: 'Android emulator/SDK state — deleting may break Android development.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 550
  },

  // ─── Project-relative (any location) ───────────────────────────────
  {
    id: 'project-git',
    platforms: ['all'],
    pathPattern: '**/.git/**',
    risk: 'PROTECTED',
    category: 'project-vcs',
    reason: 'Git repository metadata — deleting this can permanently destroy project history.',
    scanAllowed: true,
    deletionAllowed: false,
    userOverrideAllowed: false,
    priority: 850
  },
  {
    id: 'project-node-modules',
    platforms: ['all'],
    pathPattern: '**/node_modules/**',
    risk: 'CAUTION',
    category: 'project-build',
    reason:
      'Node.js dependencies — regeneratable with install, but projects will not run until restored.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 450,
    regeneratable: true
  },
  {
    id: 'project-gradle',
    platforms: ['all'],
    pathPattern: '**/.gradle/**',
    risk: 'CAUTION',
    category: 'project-build',
    reason: 'Project Gradle cache — regeneratable; the next build may be slower.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 450,
    regeneratable: true
  },
  {
    id: 'project-ios-pods',
    platforms: ['all'],
    pathPattern: '**/ios/Pods/**',
    risk: 'CAUTION',
    category: 'project-build',
    reason: 'CocoaPods dependencies — regeneratable with pod install.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 450,
    regeneratable: true
  },
  {
    id: 'project-build-dir',
    platforms: ['all'],
    pathPattern: '**/build/**',
    risk: 'CAUTION',
    category: 'project-build',
    reason: 'Build output — usually regeneratable, but confirm it is not source content.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 200,
    regeneratable: true
  },
  {
    id: 'project-dist-dir',
    platforms: ['all'],
    pathPattern: '**/dist/**',
    risk: 'CAUTION',
    category: 'project-build',
    reason: 'Build distribution output — usually regeneratable from source.',
    scanAllowed: true,
    deletionAllowed: true,
    userOverrideAllowed: true,
    priority: 200,
    regeneratable: true
  }
]
